//
//  TranslationHistoryItem.swift
//  Translate-Me
//
//  Created by Yulia E on 4/11/25.
//

import Foundation
import FirebaseFirestore

struct TranslationHistoryItem: Identifiable, Codable {
    @DocumentID var id: String? // Auto-generated by Firestore
    let originalText: String
    let translatedText: String
    let sourceLang: String
    let targetLang: String
    let timestamp: Date
}
